language: php

php:
  - 5.4
  - 5.5
  - 5.6

script: phpunit --stderr --bootstrap tests/bootstrap.php tests/tests.php

before_script:
  - travis_retry composer self-update
  - travis_retry composer install